media:
  input: images
  output: /images

content:
  - name: paginas
    label: Páginas del sitio
    type: collection
    path: .
    filename: "{primary}.html"
    view:
      fields: [title]
    fields:
      - name: title
        label: Nombre
        type: string
      - name: body
        label: Contenido
        type: code